kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: john-cluster-role-binding
  namespace: ns-1

roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: edit

subjects:
- kind: ServiceAccount
  name: john
