kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bob-deployer
  namespace: ns1

roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: deployer

subjects:
- kind: User
  apiGroup: rbac.authorization.k8s.io
  name: bob
