apiVersion: v1
kind: Service
metadata:
  name: orange-demo
  labels:
    app: orange-demo
spec:
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 80
      protocol: TCP
      name: tcp
  selector:
    app: orange-demo
  type: LoadBalancer

