apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: promehteus-ingress
#  annotations:
#    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: prometheus.test.ytsuboi.local
    http:
      paths:
      - backend:
          serviceName: prometheus-server
          servicePort: 80
