apiVersion: v1
kind: Service
metadata:
  name: nginx-snat-per-service-only-for-ns
  namespace: ncp-feature
  annotations:
    ncp/snat_pool: test-ippool-for-default    
  labels:
    feature: snat-per-service-only-for-ns 
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: tcp
  selector:
    feature: snat-per-service-only-for-ns
