apiVersion: v1
kind: ReplicationController
metadata:
  name: apple-demo-rc
  labels:
    app: apple-demo
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: apple-demo
    spec:
      containers:
      - name: apple-demo
        image: yfauser/nsx-demo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
