apiVersion: v1
kind: Service
metadata:
  name: nsx-demo-svc
  annotations:
    ncp/snat_pool: c67ce55b-49c0-4cde-a0d0-6978c2d7f977
spec:
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 80
      protocol: TCP
      name: tcp
  selector:
    snat: per-service    
