apiVersion: v1
kind: ReplicationController
metadata:
  name: other-rc
  labels:
    app: other
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: other
    spec:
      containers:
      - name: other
        image: harbor.pks.ytsuboi.local/library/testcontainer:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5001
