apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nsxt-demo-ingress
#  annotations:
#    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: vm-ware-multi.test.ytsuboi.local
    http:
      paths:
      - backend:
          serviceName: nsx-multiple-ports-service
          servicePort: 9000
