apiVersion: v1
kind: Service
metadata:
  name: nginx-service-with-sessionaffinity
  namespace: ncp-feature
  labels:
    feature: service-with-sessionaffinity 
spec:
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 600
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: tcp
  selector:
    feature: service-with-sessionaffinity
  type: LoadBalancer
