apiVersion: v1
kind: ConfigMap
metadata:
    name: prometheus-conf
data:
    prometheus.yml: |
      global:
        scrape_interval:     15s
        evaluation_interval: 30s
      rule_files:          
      scrape_configs:
      - job_name: service-kubernetes-namespaces
        kubernetes_sd_configs:
        - role: endpoints
          # api_server: 'https://localhost:1234'
          # namespaces:
          #   names:
          #     - default
      # Alerting specifies settings related to the Alertmanager.
      alerting:
        alert_relabel_configs:
        alertmanagers:
      # Settings related to the remote write feature.
      remote_write:
      remote_read:
