apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nsxdemo-multple-ports
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nsxdemo-multple-ports
    spec:
      containers:
      - name: nginx-proxy
        image: yfauser/nsx-demo
        ports:
        - name: http
          containerPort: 9000
        - name: https
          containerPort: 12201
