apiVersion: v1
kind: Service
metadata:
  name: nginx-service-with-loadbalancerip
  namespace: ncp-feature
  labels:
    feature: service-with-loadbalancerip 
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: tcp
  selector:
    feature: service-with-loadbalancerip
  type: LoadBalancer
  loadBalancerIP: 192.168.100.200
