apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nsx-demo-without-probe
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nsx-demo
        image: yfauser/nsx-demo
        ports:
        - containerPort: 80
