apiVersion: v1
kind: Service
metadata:
  name: snat-per-service-svc2
  namespace: ncp-feature
  annotations:
    ncp/snat_pool: test-ippool2
  labels:
    feature: snat-per-service      
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: tcp
  selector:
    feature: snat-per-service          