apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nsxdemo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nsxdemo
    spec:
      containers:
      - name: nsx-demo
        image: yfauser/nsx-demo
        ports:
        - name: http
          containerPort: 80
