apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nsxerrors.vmware.eng.com
spec:
  group: vmware.eng.com
  versions:
    - name: v1
      served: true
      storage: true
  version: v1
  scope: Cluster
  names:
    plural: nsxerrors
    singular: nsxerror
    kind: NSXError
    shortNames:
    - ne
  additionalPrinterColumns:
    - name: Messages
      type: string
      description: NSX error messages. Messages are sorted by timestamp on which the error occurs.
      JSONPath: .spec.message
    - name: ErrorObjectID
      type: string
      description: The identifier of the k8s object which has the errors.
      JSONPath: .spec.error-object-id
    - name: ErrorObjectType
      type: string
      description: The type of the k8s object which has the errors.
      JSONPath: .spec.error-object-type
    - name: ErrorObjectName
      type: string
      description: The name of the k8s object which has the errors.
      JSONPath: .spec.error-object-name
    - name: ErrorObjectNamespace
      type: string
      description: The namespace of the k8s object if it is namespaced. None by default
      JSONPath: .spec.error-object-ns
